/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#006a71",
        "on-surface": "#e5e2e3",
        "on-primary-fixed": "#002022",
        "tertiary-fixed-dim": "#e8c423",
        "surface-container-highest": "#353436",
        "surface-tint": "#00dbe7",
        "surface-dim": "#131314",
        "primary-fixed": "#74f5ff",
        "primary-container": "#00f2ff",
        "on-error-container": "#ffdad6",
        "secondary-container": "#7000ff",
        "tertiary-fixed": "#ffe173",
        "error": "#ffb4ab",
        "surface-bright": "#3a393a",
        "inverse-primary": "#00696f",
        "surface-variant": "#353436",
        "tertiary": "#fff6e4",
        "on-surface-variant": "#b9cacb",
        "on-secondary-fixed-variant": "#5700c9",
        "surface-container-lowest": "#0e0e0f",
        "on-primary-fixed-variant": "#004f54",
        "secondary": "#d1bcff",
        "on-error": "#690005",
        "primary": "#e1fdff",
        "outline": "#849495",
        "on-secondary": "#3c0090",
        "on-secondary-container": "#ddcdff",
        "on-secondary-fixed": "#23005b",
        "tertiary-container": "#fed83a",
        "primary-fixed-dim": "#00dbe7",
        "on-tertiary-fixed-variant": "#554500",
        "error-container": "#93000a",
        "on-primary": "#00363a",
        "surface-container-high": "#2a2a2b",
        "inverse-surface": "#e5e2e3",
        "on-tertiary-fixed": "#221b00",
        "secondary-fixed": "#e9ddff",
        "secondary-fixed-dim": "#d1bcff",
        "outline-variant": "#3a494b",
        "on-tertiary": "#3b2f00",
        "background": "#131314",
        "inverse-on-surface": "#313031",
        "surface-container": "#201f20",
        "surface": "#131314",
        "on-background": "#e5e2e3",
        "on-tertiary-container": "#725e00",
        "surface-container-low": "#1c1b1c"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
