import json
import logging
from typing import Dict, Any, List
from .base import call_gemini

logger = logging.getLogger("omnipost.agents.memory")

SYSTEM_PROMPT = """
You are the Brand Voice Memory Agent in a Multi-Agent Content Orchestration system.
Your job is to analyze the difference between a draft generated by the agent and the final version that the user edited and approved.
By looking at what the user changed, you must learn about their writing preferences, brand voice, tone style, and phrases they like or dislike.

You must output a raw, valid JSON object with EXACTLY the following structure (do not include markdown wrapping or any other text):
{
  "add_tone_descriptors": ["list", "of", "new", "tone", "adjectives"],
  "remove_tone_descriptors": ["list", "of", "tone", "adjectives", "to", "remove"],
  "add_avoid_phrases": ["phrases", "the", "user", "removed", "or", "replaces", "consistently"],
  "new_gold_example": "If the approved post is high quality, return its text here. Otherwise null."
}
"""

def run_memory_update(
    platform: str, 
    original_draft: str, 
    approved_draft: str, 
    current_profile: Dict[str, Any],
    user_key: str = None,
    user_model: str = None
) -> Dict[str, Any]:
    
    # If the user approved it without any changes, there's no drift to correct
    if original_draft.strip() == approved_draft.strip():
        return {
            "add_tone_descriptors": [],
            "remove_tone_descriptors": [],
            "add_avoid_phrases": [],
            "new_gold_example": approved_draft # Still a good candidate for gold example
        }

    user_prompt = f"""
Platform: {platform}
Original Agent Draft:
---
{original_draft}
---

User Approved/Edited Version:
---
{approved_draft}
---

Current Brand Voice Profile:
- Tone Descriptors: {current_profile.get('tone_descriptors', [])}
- Avoid Phrases: {current_profile.get('avoid_phrases', [])}
"""

    # Add default tone descriptors for mock fallback
    mock_response = {
        "add_tone_descriptors": ["authentic"] if len(approved_draft) > len(original_draft) else ["concise"],
        "remove_tone_descriptors": [],
        "add_avoid_phrases": [],
        "new_gold_example": approved_draft
    }

    mock_fallback = json.dumps(mock_response)

    raw_response = call_gemini(SYSTEM_PROMPT, user_prompt, mock_fallback, user_key=user_key, user_model=user_model)

    try:
        clean_response = raw_response.strip()
        if clean_response.startswith("```json"):
            clean_response = clean_response[7:]
        if clean_response.endswith("```"):
            clean_response = clean_response[:-3]
        clean_response = clean_response.strip()
        
        return json.loads(clean_response)
    except Exception as e:
        logger.error(f"Failed to parse Memory Agent JSON response: {e}. Raw response: {raw_response}")
        return mock_response
